project_id = "mmlovfyrjynvofhbnfqq"

[functions]
  [functions.ai-calculator]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.dedupe-content]
    verify_jwt = false
  [functions.summarize-content]
    verify_jwt = false
  [functions.sync-economic-actuals]
    verify_jwt = false
