import { Layout } from '@/components/layout/Layout';
import { PageHero } from '@/components/layout/PageHero';
import { Gift, ArrowRight, Copy, Check } from 'lucide-react';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { useState } from 'react';
import { Link } from 'react-router-dom';

const steps = [
  { step: '1', title: 'Share your link', desc: 'Share your unique referral code with friends and family.' },
  { step: '2', title: 'They sign up', desc: 'Your friend opens an account using your referral code.' },
  { step: '3', title: 'You earn rewards', desc: 'Earn 10% of their brokerage for the first year.' },
];

const ClientReferral = () => {
  const [copied, setCopied] = useState(false);
  const referralCode = 'SERNET-REF-2024';

  const handleCopy = () => {
    navigator.clipboard.writeText(referralCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Layout>
      <PageHero
        title="Client Referral"
        highlight="Programme"
        description="Love our services? Invite your friends and family to SERNET and earn attractive rewards for every successful referral."
        icon={Gift}
      />

      {/* Reward Banner */}
      <section className="section-padding bg-background">
        <div className="container-zerodha max-w-3xl">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="bg-primary/5 border border-primary/20 rounded-lg p-8 text-center">
            <h2 className="heading-lg text-foreground mb-4">Earn 10% of brokerage generated</h2>
            <p className="text-body mb-6">For every friend who opens an account and starts trading, you earn 10% of the brokerage they generate for 1 year.</p>
            <div className="bg-background rounded-lg p-4 inline-flex items-center gap-4">
              <span className="text-lg font-mono font-bold text-primary">{referralCode}</span>
              <Button size="sm" variant="outline" onClick={handleCopy}>
                {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                {copied ? 'Copied!' : 'Copy'}
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Steps */}
      <section className="section-padding bg-section-alt">
        <div className="container-zerodha max-w-3xl">
          <div className="grid md:grid-cols-3 gap-8">
            {steps.map((s, i) => (
              <motion.div key={s.step} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }} className="text-center">
                <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                  <span className="text-xl font-bold text-primary">{s.step}</span>
                </div>
                <h3 className="font-semibold text-foreground mb-2">{s.title}</h3>
                <p className="text-small">{s.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* T&C */}
      <section className="section-padding bg-background">
        <div className="container-zerodha max-w-3xl">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="bg-muted/50 rounded-lg p-6">
            <h3 className="font-semibold text-foreground mb-4">Terms & Conditions</h3>
            <ul className="text-small space-y-2">
              <li>• Referral bonus is 10% of brokerage generated by the referred customer</li>
              <li>• Bonus is paid for the first year from the date of account opening</li>
              <li>• Minimum payout threshold is ₹100</li>
              <li>• Payouts are made quarterly to your linked bank account</li>
              <li>• Self-referrals are not allowed and will be disqualified</li>
            </ul>
          </motion.div>
        </div>
      </section>
    </Layout>
  );
};

export default ClientReferral;
