import { Layout } from '@/components/layout/Layout';
import { motion } from 'framer-motion';
import { Users, Gift, ArrowRight, Copy, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useState } from 'react';

const Referral = () => {
  const [copied, setCopied] = useState(false);
  const referralCode = 'ZERODHA123';

  const handleCopy = () => {
    navigator.clipboard.writeText(referralCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Layout>
      <section className="section-padding">
        <div className="container-zerodha max-w-4xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <div className="w-16 h-16 bg-primary/10 rounded-lg flex items-center justify-center mx-auto mb-6">
              <Gift className="h-8 w-8 text-primary" />
            </div>
            <h1 className="heading-xl mb-4">
              Referral Programme
            </h1>
            <p className="text-body">
              Invite your friends to Zerodha and earn rewards
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="bg-gradient-to-br from-primary/10 to-primary/5 rounded-lg p-8 mb-12"
          >
            <div className="text-center">
              <h2 className="heading-lg mb-4">
                Earn 10% of brokerage generated
              </h2>
              <p className="text-body mb-6">
                For every friend who opens an account and starts trading, 
                you earn 10% of the brokerage they generate for 1 year.
              </p>
              
              <div className="bg-background rounded-lg p-4 inline-flex items-center gap-4">
                <span className="text-lg font-mono font-bold text-primary">{referralCode}</span>
                <Button size="sm" variant="outline" onClick={handleCopy}>
                  {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  {copied ? 'Copied!' : 'Copy'}
                </Button>
              </div>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="grid md:grid-cols-3 gap-8 mb-12"
          >
            <div className="text-center">
              <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-xl font-bold text-primary">1</span>
              </div>
              <h3 className="font-semibold text-foreground mb-2">Share your link</h3>
              <p className="text-sm text-muted-foreground">
                Share your unique referral code with friends and family
              </p>
            </div>
            <div className="text-center">
              <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-xl font-bold text-primary">2</span>
              </div>
              <h3 className="font-semibold text-foreground mb-2">They sign up</h3>
              <p className="text-sm text-muted-foreground">
                Your friend opens an account using your referral code
              </p>
            </div>
            <div className="text-center">
              <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-xl font-bold text-primary">3</span>
              </div>
              <h3 className="font-semibold text-foreground mb-2">You earn rewards</h3>
              <p className="text-sm text-muted-foreground">
                Earn 10% of their brokerage for the first year
              </p>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="bg-muted/50 rounded-lg p-6"
          >
            <h3 className="font-semibold text-foreground mb-4">Terms & Conditions</h3>
            <ul className="text-sm text-muted-foreground space-y-2">
              <li>• The referral bonus is paid as 10% of the brokerage generated by the referred customer</li>
              <li>• The bonus is paid for the first year from the date the referred customer opens an account</li>
              <li>• Minimum payout threshold is ₹100</li>
              <li>• Payouts are made quarterly to your linked bank account</li>
              <li>• Self-referrals are not allowed and will be disqualified</li>
            </ul>
          </motion.div>
        </div>
      </section>
    </Layout>
  );
};

export default Referral;
