import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Users, Building2, Briefcase, Globe, ArrowRight, Gift } from 'lucide-react';

const clientTypes = [
  {
    icon: Users,
    title: 'Individual Investors',
    description: 'From first-time investors to seasoned traders — personalized strategies for wealth creation and growth.',
    value: 'Portfolio advisory, goal-based planning, and tax-efficient investing.',
  },
  {
    icon: Building2,
    title: 'High Net Worth Individuals',
    description: 'Comprehensive wealth management for HNIs including portfolio management, tax planning, and estate planning.',
    value: 'Dedicated relationship manager, bespoke portfolio construction, and priority support.',
  },
  {
    icon: Briefcase,
    title: 'Corporate Clients',
    description: 'Treasury management, employee benefit programs, and corporate investment solutions for businesses of all sizes.',
    value: 'Customized treasury solutions, group insurance, and employee welfare programs.',
  },
  {
    icon: Globe,
    title: 'NRI Clients',
    description: 'Specialized services for Non-Resident Indians to invest seamlessly in Indian markets.',
    value: 'NRI-compliant account setup, repatriation support, and cross-border advisory.',
  },
];

const clientStats = [
  { value: '1500+', label: 'Families Served' },
  { value: '200+', label: 'Corporate Clients' },
  { value: '₹500Cr+', label: 'Assets Under Advisory' },
  { value: '18', label: 'Countries' },
];

export const ClientsNetworkContent = () => (
  <>
    {/* Stats */}
    <section className="section-padding bg-background">
      <div className="container-zerodha">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-16">
          {clientStats.map((stat, index) => (
            <motion.div key={stat.label} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5, delay: index * 0.1 }} className="text-center p-6 bg-muted/30 rounded-lg">
              <p className="stat-number">{stat.value}</p>
              <p className="stat-label mt-1">{stat.label}</p>
            </motion.div>
          ))}
        </div>

        <motion.h2 initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="heading-lg text-foreground mb-3 text-center">
          Who we serve
        </motion.h2>
        <motion.p initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: 0.1 }} className="text-body text-center mb-12 max-w-2xl mx-auto">
          Tailored financial solutions for every type of investor.
        </motion.p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {clientTypes.map((type, index) => (
            <motion.div key={type.title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5, delay: index * 0.08 }} className="feature-card">
              <div className="flex items-center gap-4 mb-4">
                <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center">
                  <type.icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="heading-md text-foreground">{type.title}</h3>
              </div>
              <p className="text-body text-sm mb-3">{type.description}</p>
              <p className="text-small italic border-l-2 border-primary/30 pl-3">{type.value}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>

    {/* Referral CTA */}
    <section className="section-padding bg-section-alt">
      <div className="container-zerodha">
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="max-w-3xl mx-auto p-8 rounded-lg border border-primary/20 bg-primary/5 text-center">
          <Gift className="w-10 h-10 text-primary mx-auto mb-4" />
          <h3 className="heading-md text-foreground mb-3">Client Referral Programme</h3>
          <p className="text-body text-sm mb-6 max-w-xl mx-auto">
            Love our services? Refer your friends and family and earn rewards. Earn 10% of brokerage generated by your referrals for the first year.
          </p>
          <Link to="/referral/client" className="btn-primary inline-flex items-center">
            Learn more <ArrowRight className="ml-2 h-4 w-4" />
          </Link>
        </motion.div>
      </div>
    </section>
  </>
);
